import "../styles/sass/_index.scss";
import SocketsProvider from "@/context/socket.context";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><SocketsProvider>{children}</SocketsProvider></body>
    </html>
  )
}
